services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Passw0rd1
      POSTGRES_USER: postgres
      POSTGRES_DB: microblog
    ports:
      - 5432:5432
  web:
    build:
      dockerfile: Dockerfile
    image: web
    env_file:
      - envs/.env.dev
    environment:
     - MICROBLOG_DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
