# Generated by Django 4.2.3 on 2023-07-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_alter_hashtag_options'),
        ('posts', '0002_remove_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(to='hashtags.hashtag'),
        ),
    ]
